import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

const handler = createPagesFunctionHandler({
  build: serverBuild,
});

export function onRequest(context) {
  return handler(context.request, context.env, context);
}
