name: CI/CD

on:
  push:
    branches:
      - main
#      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run build
        run: pnpm run build

      - name: Run ESLint
        run: pnpm run lint

      - name: Wrangler Deploy
        run: wrangler pages deploy

#  build:
#    runs-on: ...
#    steps:
#      - uses: actions/checkout@v3

#      # ... some other preparation steps (dependencies, compilation as a separate step, etc) ...

#      - name: Setup Testcontainers Cloud Client
#        uses: atomicjar/testcontainers-cloud-setup-action@v1
#        with:
#        token: ${{ secrets.TC_CLOUD_TOKEN }}


      # ... existing steps executing your Testcontainers tests go here ...

